### ISSUE TITLE
Change request to the list of searx instances 

### ISSUE THREAD

**Issue by return42** [dalf/searx-stats2#12]
If you want to see your searx instance added or removed from https://searx.space/ list, please add a comment here.

**Comment by return42** [comment]
@nibble-hub requests to add his instance, see https://github.com/asciimoo/searx/pull/1818

**Comment by nibble-hub** [comment]
please add https://nibblehole.com

**Comment by dalf** [comment]
See https://github.com/dalf/searx-instances
