### ISSUE TITLE
Vanilla Searx instance get flagged as Cjs

### ISSUE THREAD

**Issue by unixfox** [dalf/searx-stats2#36]
asciimoo just introduced a new file called "translations.js" in the Searx source code: https://github.com/asciimoo/searx/commit/4ca0d8cb0fd6c0e6b1301a6e8577aea6d928e9dc

Since this commit it seems like searx.space flags all the Searx instances as Cjs that have the newer code with the "translations.js" file.

![image](https://user-images.githubusercontent.com/4016501/85070281-1055cc80-b1a5-11ea-83d4-1d12c39891d0.png)
![image](https://user-images.githubusercontent.com/4016501/85070307-1b106180-b1a5-11ea-95cf-589456422075.png)

**Comment by dalf** [comment]
The bullet proof solution is to call the searx application for each commit : https://www.python-httpx.org/advanced/#calling-into-python-web-apps

Since it is a small (mostly) static file, an easy solution is to hard code the hash (actually put the actually, and hash it).
