### ISSUE TITLE
Instances.json file contains removed engines from searx master

### ISSUE THREAD

**Issue by HLFH** [dalf/searx-stats2#39]
Hi,

The [`instances.json`](https://searx.space/data/instances.json) file contains data about removed engines.

Two examples are:

 - [faroo](https://github.com/asciimoo/searx/pull/1923)
 - [asksteem](https://github.com/asciimoo/searx/pull/1501)

On `searx.space` engines tab, either we remove the columns of engines that have been removed from searx master, or we should add a `⚠️` warning sign to the `faroo` and `asksteem` rows of searx instances that are still listing these removed engines from searx master:

<img width="34" alt="Screenshot 2020-04-21 at 11 44 55" src="https://user-images.githubusercontent.com/2359059/79857348-8fa56a80-83c5-11ea-829e-cd67ef9604ad.png">

And maybe for searx instances that are correctly updated and don't list some removed engines, we should precise with this kind of icon in the related rows:

<img width="37" alt="minus-in-circle" src="https://user-images.githubusercontent.com/2359059/79856944-eeb6af80-83c4-11ea-837c-5a2cf31a8b70.png">

I don't know which code has to be changed for that. 

Best is to add these two signs and if some searx instances have not been updated in 90 days or so, they should be removed from the list of available searx instances.

**Comment by dalf** [comment]
A long term solution idea:
* parse searx/settings.yml
* first: enable engine, second: disable engne, third: unknown engine (not declare in searx/settings.yml)
* there is already a clone of the searx repository to get all the static file hashes: 
  * https://github.com/dalf/searx-stats2/blob/master/searxstats/data/well_kown_hashes.py#L98
  * https://github.com/dalf/searx-stats2/blob/master/searxstats/config.py#L52
