### ISSUE TITLE
Connection Timeout on some instance

### ISSUE THREAD

**Issue by dalf** [dalf/searx-stats2#43]
For reference: https://github.com/dalf/cryptcheck-backend/issues/1#issuecomment-650531032

searx-stats2 has some "Connection Timeout" error despite a reliable searx instance.

I have been able to reproduce the connection timeout with this code ( httpx==0.11.0 )
```python
import httpx
async with httpx.AsyncClient() as c:
   r = await c.get('https://searx.be')
```

```
TimeoutError                              Traceback (most recent call last)
~/ve/lib/python3.7/site-packages/httpx/backends/asyncio.py in open_tcp_stream(self, hostname, port, ssl_context, timeout)
    198                     asyncio.open_connection(hostname, port, ssl=ssl_context),
--> 199                     timeout.connect_timeout,
    200                 )

/usr/lib/python3.7/asyncio/tasks.py in wait_for(fut, timeout, loop)
    422             await _cancel_and_wait(fut, loop=loop)
--> 423             raise futures.TimeoutError()
    424     finally:

TimeoutError: 

During handling of the above exception, another exception occurred:

ConnectTimeout                            Traceback (most recent call last)
<ipython-input-2-5d9ab2d17d71> in async-def-wrapper()

~/ve/lib/python3.7/site-packages/httpx/client.py in get(self, url, params, headers, cookies, auth, allow_redirects, timeout)
   1235             auth=auth,
   1236             allow_redirects=allow_redirects,
-> 1237             timeout=timeout,
   1238         )
   1239 
```

Note: the bug won't appear immediately after, I have to wait few minutes before the same error appears. 

The last httpx version (0.13.3) seems to fix the problem.

**Comment by unixfox** [comment]
Maybe it's the same issue as you described here: https://github.com/dalf/cryptcheck-backend/issues/1#issuecomment-654296951?

**Comment by dalf** [comment]
@unixfox yes, I see the same "TCP retransmission" packets, and then "Connection Timeout" in the Python log.

Some instances may have allowed the [searx.space IP](https://github.com/searx/searx-docker/blob/2487c1397ca35c028a87be0d4cca0d9445ce3afb/rules.json#L4) to bypass filtron.
So if searx-stats2 runs on a different IPs, it will take time to update the filters.

**Comment by dalf** [comment]
FYI, now searx-stats2 runs on check.searx.space (same VPS).
There is less connection issues.

As expected, some instances blocks the new IPs (for example https://searx.hlfh.space/ hosted by @HLFH ).

I'm going to update searx-docker, but it would be useful to reference the host name rather than the IPs. See https://github.com/asciimoo/filtron/issues/12

**Comment by dalf** [comment]
I don't see any more "Connection Timeout" errors. I close the issue.
