### ISSUE TITLE
Why is response time prefered over an instance that didn't implement any CSP?

### ISSUE THREAD

**Issue by unixfox** [dalf/searx-stats2#8]
![Screenshot_2020-01-06 Searx statistics](https://user-images.githubusercontent.com/4016501/71814070-aa084200-307b-11ea-937c-cdd0259ea10e.png)
Why for example `https://search.seds.nl/` have a higher ranking than `https://roteserver.de/searx/`?
Shouldn't security be a higher factor than a better response time?

**Comment by dalf** [comment]
Actually, the sort order is puzzling me.

[Currently it is](https://github.com/dalf/searx-stats2/blob/master/html/main.js#L26-L27) : 

| column | description | note |
|---|---|---|
| http.status_code | HTTP status code of the Initial Response time | if different from 200, the instance is not Online |
| error | [httpx](https://github.com/dalf/searx-stats2/blob/e3812b913cecd9751c3995116d8258f69cddb0fc/searxstats/common/http.py#L87) error on the Initial Response Time | if not None, the instance is not Online |
| version | from [```<meta name="generator"```](https://github.com/dalf/searx-stats2/blob/master/searxstats/fetcher/basic.py#L12) in the index page | the sort algorithm ignores suffix like ```-unknown``` and ```-407-17b6faa4``` |
| tls.grade | from [cryptcheck](https://cryptcheck.fr/) | is it the link from the browser to the searx instance secure ? |
| html.grade | vanilla or modified templates | does it run code from github, same host, external host  ? |
| timing.initial | response time of the initial request | |
| http.grade (CSP) | from [observatory.mozilla.org](https://observatory.mozilla.org) | Safety net: avoid XSS or bugs leading to unwanted requests. |
| url | | follow redirect |

A better order is:
- No error
  - http.status_code
  - error
- Version first
  - version (default filter value : last searx version).
- Security (perhaps this section should be before the version ?)
  - tls.grade (default filter value: 'A')
  - http.grade (default filter value: 'A'). I don't know which one should be first between http.grade and html.grade
  - html.grade (default filter value: empty)
- Timing:
  - timing.initial
- url

With: 
- ipv6: unchecked by default.
- remove network with privacy issue by default.
- google checkbox: unchecked.

Some numbers:
* searx.be is the only instance have:
  * CSP grade A
  * TLS grade A
  * IPv6
  * support google.
* 24 instances have the CSP grade A+
* between 10 to 18 instances support google (the number is changing everyday).
* 8 instances are behind Cloudflare

**Comment by unixfox** [comment]
I do prefer the proposed new order.
I think the version should come before the security because if an instance is unusable due to its old version the visitor will just leave without really using it for his personal searches.

**Comment by unixfox** [comment]
I saw your fix https://github.com/dalf/searx-stats2/commit/37beff96a130641bd319457ef33716c1a43f9ff1.
I still don't know if by default that's better to have the HTTP grade before or after the CSP.
On one hand CSP is important for security but on the other hand HTTP grade is also important for privacy.

**Comment by dalf** [comment]
The initial issue is fixed. We can create another one about the order between HTTP grade and CSP grade.
